name: Deploy Tako Customer Review

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - develop
  #     - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@main

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          # script: |
          #   echo "SSH Connection Successful"
          script: |
            cd production/tako-customer-review
            git remote set-url origin git@github.com:Fantocaa/tako-customer-review.git

            git fetch --all
            git reset --hard origin/main
            git clean -fd

            composer install --no-dev --prefer-dist
            php artisan migrate --database=tako-perusahaan --path=database/migrations/perusahaan
            php artisan migrate --database=tako-customer --path=database/migrations/customer

            if command -v node > /dev/null 2>&1; then
              echo "Node.js sudah terinstall: $(node -v)"
            else
              echo "Node.js belum terinstall. Silakan install Node.js versi LTS."
              exit 1
            fi

            if command -v npm > /dev/null 2>&1; then
              echo "npm sudah terinstall: $(npm -v)"
            else
              echo "npm belum terinstall! Menginstall npm via NVM..."
              export NVM_DIR="$HOME/.nvm"
              if [ ! -d "$NVM_DIR" ]; then
                mkdir -p "$NVM_DIR"
                curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.6/install.sh | bash
              fi
              # load nvm
              export NVM_DIR="$HOME/.nvm"
              [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

              nvm install --lts
              nvm use --lts
              echo "npm version: $(npm -v)"
            fi

            echo "Install frontend dependencies dan build"
            npm ci
            npm run build

            echo "Deploy selesai âœ…"
